export interface Course {
    _id: string,
    term: string,
    type: string,
    code: string,
    units: string,
    title: string,
    description?: string,
    professor?: string,
    section?: string,
    midterm?: string,
    final?: string,
    status: string,
    modules?: [string],
};